/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pf_and_J_codegen_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[47] = {12, 12, 0, 2, 5, 8, 10, 13, 16, 18, 21, 24, 26, 29, 32, 4, 5, 3, 4, 5, 3, 4, 5, 1, 2, 0, 1, 2, 0, 1, 2, 10, 11, 9, 10, 11, 9, 10, 11, 7, 8, 6, 7, 8, 6, 7, 8};
static const casadi_int casadi_s2[47] = {12, 12, 0, 3, 5, 8, 11, 13, 16, 19, 21, 24, 27, 29, 32, 0, 1, 2, 1, 2, 0, 1, 2, 3, 4, 5, 4, 5, 3, 4, 5, 6, 7, 8, 7, 8, 6, 7, 8, 9, 10, 11, 10, 11, 9, 10, 11};
static const casadi_int casadi_s3[87] = {144, 12, 0, 8, 10, 18, 26, 28, 36, 44, 46, 54, 62, 64, 72, 37, 38, 48, 49, 50, 60, 61, 62, 37, 38, 37, 38, 48, 49, 50, 60, 61, 62, 4, 5, 15, 16, 17, 27, 28, 29, 4, 5, 4, 5, 15, 16, 17, 27, 28, 29, 115, 116, 126, 127, 128, 138, 139, 140, 115, 116, 115, 116, 126, 127, 128, 138, 139, 140, 82, 83, 93, 94, 95, 105, 106, 107, 82, 83, 82, 83, 93, 94, 95, 105, 106, 107};

/* pf_and_J:(q[12],theta[12])->(y[12],Jy[12x12,32nz],DyDtheta[12x12,32nz],dJy_dtheta[144x12,72nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=3.4549999999999997e-01;
  a1=-3.4999999999999998e-01;
  a2=arg[0]? arg[0][4] : 0;
  a3=sin(a2);
  a4=(a1*a3);
  a4=(a0+a4);
  a5=cos(a2);
  a6=arg[0]? arg[0][5] : 0;
  a7=sin(a6);
  a8=(a5*a7);
  a9=cos(a6);
  a10=(a3*a9);
  a8=(a8+a10);
  a10=(a1*a8);
  a4=(a4+a10);
  a10=(a5*a9);
  a11=(a3*a7);
  a10=(a10-a11);
  a11=arg[1]? arg[1][0] : 0;
  a12=(a10*a11);
  a13=arg[1]? arg[1][2] : 0;
  a14=(a8*a13);
  a12=(a12+a14);
  a4=(a4+a12);
  if (res[0]!=0) res[0][0]=a4;
  a4=-7.1999999999999995e-02;
  a12=-1.2675000000000000e-01;
  a14=arg[0]? arg[0][3] : 0;
  a15=cos(a14);
  a16=(a12*a15);
  a16=(a4+a16);
  a17=sin(a14);
  a18=(a17*a5);
  a19=(a1*a18);
  a16=(a16-a19);
  a19=(a17*a3);
  a20=(a19*a7);
  a21=(a18*a9);
  a20=(a20-a21);
  a21=(a1*a20);
  a16=(a16+a21);
  a21=(a19*a9);
  a22=(a18*a7);
  a21=(a21+a22);
  a22=(a21*a11);
  a23=arg[1]? arg[1][1] : 0;
  a24=(a15*a23);
  a22=(a22+a24);
  a24=(a20*a13);
  a22=(a22+a24);
  a16=(a16+a22);
  if (res[0]!=0) res[0][1]=a16;
  a16=(a12*a17);
  a22=(a15*a5);
  a24=(a1*a22);
  a16=(a16+a24);
  a24=(a22*a9);
  a25=(a15*a3);
  a26=(a25*a7);
  a24=(a24-a26);
  a26=(a1*a24);
  a16=(a16+a26);
  a26=(a17*a23);
  a27=(a25*a9);
  a28=(a22*a7);
  a27=(a27+a28);
  a28=(a27*a11);
  a26=(a26-a28);
  a28=(a24*a13);
  a26=(a26+a28);
  a16=(a16+a26);
  if (res[0]!=0) res[0][2]=a16;
  a16=arg[0]? arg[0][1] : 0;
  a26=sin(a16);
  a28=(a1*a26);
  a0=(a0+a28);
  a28=cos(a16);
  a29=arg[0]? arg[0][2] : 0;
  a30=sin(a29);
  a31=(a28*a30);
  a32=cos(a29);
  a33=(a26*a32);
  a31=(a31+a33);
  a33=(a1*a31);
  a0=(a0+a33);
  a33=(a28*a32);
  a34=(a26*a30);
  a33=(a33-a34);
  a34=arg[1]? arg[1][3] : 0;
  a35=(a33*a34);
  a36=arg[1]? arg[1][5] : 0;
  a37=(a31*a36);
  a35=(a35+a37);
  a0=(a0+a35);
  if (res[0]!=0) res[0][3]=a0;
  a0=7.1999999999999995e-02;
  a35=1.2675000000000000e-01;
  a37=arg[0]? arg[0][0] : 0;
  a38=cos(a37);
  a39=(a35*a38);
  a39=(a0+a39);
  a40=sin(a37);
  a41=(a40*a28);
  a42=(a1*a41);
  a39=(a39-a42);
  a42=(a40*a26);
  a43=(a42*a30);
  a44=(a41*a32);
  a43=(a43-a44);
  a44=(a1*a43);
  a39=(a39+a44);
  a44=(a42*a32);
  a45=(a41*a30);
  a44=(a44+a45);
  a45=(a44*a34);
  a46=arg[1]? arg[1][4] : 0;
  a47=(a38*a46);
  a45=(a45+a47);
  a47=(a43*a36);
  a45=(a45+a47);
  a39=(a39+a45);
  if (res[0]!=0) res[0][4]=a39;
  a39=(a35*a40);
  a45=(a38*a28);
  a47=(a1*a45);
  a39=(a39+a47);
  a47=(a45*a32);
  a48=(a38*a26);
  a49=(a48*a30);
  a47=(a47-a49);
  a49=(a1*a47);
  a39=(a39+a49);
  a49=(a40*a46);
  a50=(a48*a32);
  a51=(a45*a30);
  a50=(a50+a51);
  a51=(a50*a34);
  a49=(a49-a51);
  a51=(a47*a36);
  a49=(a49+a51);
  a39=(a39+a49);
  if (res[0]!=0) res[0][5]=a39;
  a39=-3.4549999999999997e-01;
  a49=arg[0]? arg[0][10] : 0;
  a51=sin(a49);
  a52=(a1*a51);
  a52=(a39+a52);
  a53=cos(a49);
  a54=arg[0]? arg[0][11] : 0;
  a55=sin(a54);
  a56=(a53*a55);
  a57=cos(a54);
  a58=(a51*a57);
  a56=(a56+a58);
  a58=(a1*a56);
  a52=(a52+a58);
  a58=(a53*a57);
  a59=(a51*a55);
  a58=(a58-a59);
  a59=arg[1]? arg[1][6] : 0;
  a60=(a58*a59);
  a61=arg[1]? arg[1][8] : 0;
  a62=(a56*a61);
  a60=(a60+a62);
  a52=(a52+a60);
  if (res[0]!=0) res[0][6]=a52;
  a52=arg[0]? arg[0][9] : 0;
  a60=cos(a52);
  a62=(a12*a60);
  a4=(a4+a62);
  a62=sin(a52);
  a63=(a62*a53);
  a64=(a1*a63);
  a4=(a4-a64);
  a64=(a62*a51);
  a65=(a64*a55);
  a66=(a63*a57);
  a65=(a65-a66);
  a66=(a1*a65);
  a4=(a4+a66);
  a66=(a64*a57);
  a67=(a63*a55);
  a66=(a66+a67);
  a67=(a66*a59);
  a68=arg[1]? arg[1][7] : 0;
  a69=(a60*a68);
  a67=(a67+a69);
  a69=(a65*a61);
  a67=(a67+a69);
  a4=(a4+a67);
  if (res[0]!=0) res[0][7]=a4;
  a4=(a12*a62);
  a67=(a60*a53);
  a69=(a1*a67);
  a4=(a4+a69);
  a69=(a67*a57);
  a70=(a60*a51);
  a71=(a70*a55);
  a69=(a69-a71);
  a71=(a1*a69);
  a4=(a4+a71);
  a71=(a62*a68);
  a72=(a70*a57);
  a73=(a67*a55);
  a72=(a72+a73);
  a73=(a72*a59);
  a71=(a71-a73);
  a73=(a69*a61);
  a71=(a71+a73);
  a4=(a4+a71);
  if (res[0]!=0) res[0][8]=a4;
  a4=arg[0]? arg[0][7] : 0;
  a71=sin(a4);
  a73=(a1*a71);
  a39=(a39+a73);
  a73=cos(a4);
  a74=arg[0]? arg[0][8] : 0;
  a75=sin(a74);
  a76=(a73*a75);
  a77=cos(a74);
  a78=(a71*a77);
  a76=(a76+a78);
  a78=(a1*a76);
  a39=(a39+a78);
  a78=(a73*a77);
  a79=(a71*a75);
  a78=(a78-a79);
  a79=arg[1]? arg[1][9] : 0;
  a80=(a78*a79);
  a81=arg[1]? arg[1][11] : 0;
  a82=(a76*a81);
  a80=(a80+a82);
  a39=(a39+a80);
  if (res[0]!=0) res[0][9]=a39;
  a39=arg[0]? arg[0][6] : 0;
  a80=cos(a39);
  a82=(a35*a80);
  a0=(a0+a82);
  a82=sin(a39);
  a83=(a82*a73);
  a84=(a1*a83);
  a0=(a0-a84);
  a84=(a82*a71);
  a85=(a84*a75);
  a86=(a83*a77);
  a85=(a85-a86);
  a86=(a1*a85);
  a0=(a0+a86);
  a86=(a84*a77);
  a87=(a83*a75);
  a86=(a86+a87);
  a87=(a86*a79);
  a88=arg[1]? arg[1][10] : 0;
  a89=(a80*a88);
  a87=(a87+a89);
  a89=(a85*a81);
  a87=(a87+a89);
  a0=(a0+a87);
  if (res[0]!=0) res[0][10]=a0;
  a0=(a35*a82);
  a87=(a80*a73);
  a89=(a1*a87);
  a0=(a0+a89);
  a89=(a87*a77);
  a90=(a80*a71);
  a91=(a90*a75);
  a89=(a89-a91);
  a91=(a1*a89);
  a0=(a0+a91);
  a91=(a82*a88);
  a92=(a90*a77);
  a93=(a87*a75);
  a92=(a92+a93);
  a93=(a92*a79);
  a91=(a91-a93);
  a93=(a89*a81);
  a91=(a91+a93);
  a0=(a0+a91);
  if (res[0]!=0) res[0][11]=a0;
  a0=cos(a37);
  a91=(a26*a0);
  a93=(a30*a91);
  a94=(a28*a0);
  a95=(a32*a94);
  a93=(a93-a95);
  a95=(a1*a93);
  a37=sin(a37);
  a96=(a35*a37);
  a97=(a1*a94);
  a96=(a96+a97);
  a95=(a95-a96);
  a91=(a32*a91);
  a94=(a30*a94);
  a91=(a91+a94);
  a94=(a34*a91);
  a96=(a46*a37);
  a94=(a94-a96);
  a96=(a36*a93);
  a94=(a94+a96);
  a95=(a95+a94);
  if (res[1]!=0) res[1][0]=a95;
  a95=(a35*a0);
  a94=(a28*a37);
  a96=(a1*a94);
  a95=(a95-a96);
  a96=(a26*a37);
  a97=(a30*a96);
  a98=(a32*a94);
  a97=(a97-a98);
  a98=(a1*a97);
  a95=(a95+a98);
  a46=(a46*a0);
  a96=(a32*a96);
  a94=(a30*a94);
  a96=(a96+a94);
  a94=(a34*a96);
  a46=(a46+a94);
  a94=(a36*a97);
  a46=(a46+a94);
  a95=(a95+a46);
  if (res[1]!=0) res[1][1]=a95;
  a95=cos(a16);
  a46=(a1*a95);
  a94=(a32*a95);
  a16=sin(a16);
  a98=(a30*a16);
  a94=(a94-a98);
  a98=(a1*a94);
  a46=(a46+a98);
  a98=(a36*a94);
  a99=(a32*a16);
  a100=(a30*a95);
  a99=(a99+a100);
  a100=(a34*a99);
  a98=(a98-a100);
  a46=(a46+a98);
  if (res[1]!=0) res[1][2]=a46;
  a46=(a40*a16);
  a98=(a1*a46);
  a100=(a40*a95);
  a101=(a30*a100);
  a102=(a32*a46);
  a101=(a101+a102);
  a102=(a1*a101);
  a98=(a98+a102);
  a100=(a32*a100);
  a46=(a30*a46);
  a100=(a100-a46);
  a46=(a34*a100);
  a102=(a36*a101);
  a46=(a46+a102);
  a98=(a98+a46);
  if (res[1]!=0) res[1][3]=a98;
  a16=(a38*a16);
  a98=(a1*a16);
  a46=(a32*a16);
  a95=(a38*a95);
  a102=(a30*a95);
  a46=(a46+a102);
  a102=(a1*a46);
  a98=(a98+a102);
  a32=(a32*a95);
  a30=(a30*a16);
  a32=(a32-a30);
  a30=(a34*a32);
  a16=(a36*a46);
  a30=(a30+a16);
  a98=(a98+a30);
  a98=(-a98);
  if (res[1]!=0) res[1][4]=a98;
  a98=cos(a29);
  a30=(a28*a98);
  a29=sin(a29);
  a16=(a26*a29);
  a30=(a30-a16);
  a16=(a1*a30);
  a95=(a36*a30);
  a28=(a28*a29);
  a26=(a26*a98);
  a28=(a28+a26);
  a26=(a34*a28);
  a95=(a95-a26);
  a16=(a16+a95);
  if (res[1]!=0) res[1][5]=a16;
  a16=(a42*a98);
  a95=(a41*a29);
  a16=(a16+a95);
  a95=(a1*a16);
  a41=(a41*a98);
  a42=(a42*a29);
  a41=(a41-a42);
  a42=(a34*a41);
  a26=(a36*a16);
  a42=(a42+a26);
  a95=(a95+a42);
  if (res[1]!=0) res[1][6]=a95;
  a95=(a45*a29);
  a42=(a48*a98);
  a95=(a95+a42);
  a42=(a1*a95);
  a45=(a45*a98);
  a48=(a48*a29);
  a45=(a45-a48);
  a34=(a34*a45);
  a36=(a36*a95);
  a34=(a34+a36);
  a42=(a42+a34);
  a42=(-a42);
  if (res[1]!=0) res[1][7]=a42;
  a42=cos(a14);
  a34=(a3*a42);
  a36=(a7*a34);
  a48=(a5*a42);
  a29=(a9*a48);
  a36=(a36-a29);
  a29=(a1*a36);
  a14=sin(a14);
  a98=(a12*a14);
  a26=(a1*a48);
  a98=(a98+a26);
  a29=(a29-a98);
  a34=(a9*a34);
  a48=(a7*a48);
  a34=(a34+a48);
  a48=(a11*a34);
  a98=(a23*a14);
  a48=(a48-a98);
  a98=(a13*a36);
  a48=(a48+a98);
  a29=(a29+a48);
  if (res[1]!=0) res[1][8]=a29;
  a29=(a12*a42);
  a48=(a5*a14);
  a98=(a1*a48);
  a29=(a29-a98);
  a98=(a3*a14);
  a26=(a7*a98);
  a102=(a9*a48);
  a26=(a26-a102);
  a102=(a1*a26);
  a29=(a29+a102);
  a23=(a23*a42);
  a98=(a9*a98);
  a48=(a7*a48);
  a98=(a98+a48);
  a48=(a11*a98);
  a23=(a23+a48);
  a48=(a13*a26);
  a23=(a23+a48);
  a29=(a29+a23);
  if (res[1]!=0) res[1][9]=a29;
  a29=cos(a2);
  a23=(a1*a29);
  a48=(a9*a29);
  a2=sin(a2);
  a102=(a7*a2);
  a48=(a48-a102);
  a102=(a1*a48);
  a23=(a23+a102);
  a102=(a13*a48);
  a103=(a9*a2);
  a104=(a7*a29);
  a103=(a103+a104);
  a104=(a11*a103);
  a102=(a102-a104);
  a23=(a23+a102);
  if (res[1]!=0) res[1][10]=a23;
  a23=(a17*a2);
  a102=(a1*a23);
  a104=(a17*a29);
  a105=(a7*a104);
  a106=(a9*a23);
  a105=(a105+a106);
  a106=(a1*a105);
  a102=(a102+a106);
  a104=(a9*a104);
  a23=(a7*a23);
  a104=(a104-a23);
  a23=(a11*a104);
  a106=(a13*a105);
  a23=(a23+a106);
  a102=(a102+a23);
  if (res[1]!=0) res[1][11]=a102;
  a2=(a15*a2);
  a102=(a1*a2);
  a23=(a9*a2);
  a29=(a15*a29);
  a106=(a7*a29);
  a23=(a23+a106);
  a106=(a1*a23);
  a102=(a102+a106);
  a9=(a9*a29);
  a7=(a7*a2);
  a9=(a9-a7);
  a7=(a11*a9);
  a2=(a13*a23);
  a7=(a7+a2);
  a102=(a102+a7);
  a102=(-a102);
  if (res[1]!=0) res[1][12]=a102;
  a102=cos(a6);
  a7=(a5*a102);
  a6=sin(a6);
  a2=(a3*a6);
  a7=(a7-a2);
  a2=(a1*a7);
  a29=(a13*a7);
  a5=(a5*a6);
  a3=(a3*a102);
  a5=(a5+a3);
  a3=(a11*a5);
  a29=(a29-a3);
  a2=(a2+a29);
  if (res[1]!=0) res[1][13]=a2;
  a2=(a19*a102);
  a29=(a18*a6);
  a2=(a2+a29);
  a29=(a1*a2);
  a18=(a18*a102);
  a19=(a19*a6);
  a18=(a18-a19);
  a19=(a11*a18);
  a3=(a13*a2);
  a19=(a19+a3);
  a29=(a29+a19);
  if (res[1]!=0) res[1][14]=a29;
  a29=(a22*a6);
  a19=(a25*a102);
  a29=(a29+a19);
  a19=(a1*a29);
  a22=(a22*a102);
  a25=(a25*a6);
  a22=(a22-a25);
  a11=(a11*a22);
  a13=(a13*a29);
  a11=(a11+a13);
  a19=(a19+a11);
  a19=(-a19);
  if (res[1]!=0) res[1][15]=a19;
  a19=cos(a39);
  a11=(a71*a19);
  a13=(a75*a11);
  a25=(a73*a19);
  a6=(a77*a25);
  a13=(a13-a6);
  a6=(a1*a13);
  a39=sin(a39);
  a102=(a35*a39);
  a3=(a1*a25);
  a102=(a102+a3);
  a6=(a6-a102);
  a11=(a77*a11);
  a25=(a75*a25);
  a11=(a11+a25);
  a25=(a79*a11);
  a102=(a88*a39);
  a25=(a25-a102);
  a102=(a81*a13);
  a25=(a25+a102);
  a6=(a6+a25);
  if (res[1]!=0) res[1][16]=a6;
  a35=(a35*a19);
  a6=(a73*a39);
  a25=(a1*a6);
  a35=(a35-a25);
  a25=(a71*a39);
  a102=(a75*a25);
  a3=(a77*a6);
  a102=(a102-a3);
  a3=(a1*a102);
  a35=(a35+a3);
  a88=(a88*a19);
  a25=(a77*a25);
  a6=(a75*a6);
  a25=(a25+a6);
  a6=(a79*a25);
  a88=(a88+a6);
  a6=(a81*a102);
  a88=(a88+a6);
  a35=(a35+a88);
  if (res[1]!=0) res[1][17]=a35;
  a35=cos(a4);
  a88=(a1*a35);
  a6=(a77*a35);
  a4=sin(a4);
  a3=(a75*a4);
  a6=(a6-a3);
  a3=(a1*a6);
  a88=(a88+a3);
  a3=(a81*a6);
  a106=(a77*a4);
  a107=(a75*a35);
  a106=(a106+a107);
  a107=(a79*a106);
  a3=(a3-a107);
  a88=(a88+a3);
  if (res[1]!=0) res[1][18]=a88;
  a88=(a82*a4);
  a3=(a1*a88);
  a107=(a82*a35);
  a108=(a75*a107);
  a109=(a77*a88);
  a108=(a108+a109);
  a109=(a1*a108);
  a3=(a3+a109);
  a107=(a77*a107);
  a88=(a75*a88);
  a107=(a107-a88);
  a88=(a79*a107);
  a109=(a81*a108);
  a88=(a88+a109);
  a3=(a3+a88);
  if (res[1]!=0) res[1][19]=a3;
  a4=(a80*a4);
  a3=(a1*a4);
  a88=(a77*a4);
  a35=(a80*a35);
  a109=(a75*a35);
  a88=(a88+a109);
  a109=(a1*a88);
  a3=(a3+a109);
  a77=(a77*a35);
  a75=(a75*a4);
  a77=(a77-a75);
  a75=(a79*a77);
  a4=(a81*a88);
  a75=(a75+a4);
  a3=(a3+a75);
  a3=(-a3);
  if (res[1]!=0) res[1][20]=a3;
  a3=cos(a74);
  a75=(a73*a3);
  a74=sin(a74);
  a4=(a71*a74);
  a75=(a75-a4);
  a4=(a1*a75);
  a35=(a81*a75);
  a73=(a73*a74);
  a71=(a71*a3);
  a73=(a73+a71);
  a71=(a79*a73);
  a35=(a35-a71);
  a4=(a4+a35);
  if (res[1]!=0) res[1][21]=a4;
  a4=(a84*a3);
  a35=(a83*a74);
  a4=(a4+a35);
  a35=(a1*a4);
  a83=(a83*a3);
  a84=(a84*a74);
  a83=(a83-a84);
  a84=(a79*a83);
  a71=(a81*a4);
  a84=(a84+a71);
  a35=(a35+a84);
  if (res[1]!=0) res[1][22]=a35;
  a35=(a87*a74);
  a84=(a90*a3);
  a35=(a35+a84);
  a84=(a1*a35);
  a87=(a87*a3);
  a90=(a90*a74);
  a87=(a87-a90);
  a79=(a79*a87);
  a81=(a81*a35);
  a79=(a79+a81);
  a84=(a84+a79);
  a84=(-a84);
  if (res[1]!=0) res[1][23]=a84;
  a84=cos(a52);
  a79=(a51*a84);
  a81=(a55*a79);
  a90=(a53*a84);
  a74=(a57*a90);
  a81=(a81-a74);
  a74=(a1*a81);
  a52=sin(a52);
  a3=(a12*a52);
  a71=(a1*a90);
  a3=(a3+a71);
  a74=(a74-a3);
  a79=(a57*a79);
  a90=(a55*a90);
  a79=(a79+a90);
  a90=(a59*a79);
  a3=(a68*a52);
  a90=(a90-a3);
  a3=(a61*a81);
  a90=(a90+a3);
  a74=(a74+a90);
  if (res[1]!=0) res[1][24]=a74;
  a12=(a12*a84);
  a74=(a53*a52);
  a90=(a1*a74);
  a12=(a12-a90);
  a90=(a51*a52);
  a3=(a55*a90);
  a71=(a57*a74);
  a3=(a3-a71);
  a71=(a1*a3);
  a12=(a12+a71);
  a68=(a68*a84);
  a90=(a57*a90);
  a74=(a55*a74);
  a90=(a90+a74);
  a74=(a59*a90);
  a68=(a68+a74);
  a74=(a61*a3);
  a68=(a68+a74);
  a12=(a12+a68);
  if (res[1]!=0) res[1][25]=a12;
  a12=cos(a49);
  a68=(a1*a12);
  a74=(a57*a12);
  a49=sin(a49);
  a71=(a55*a49);
  a74=(a74-a71);
  a71=(a1*a74);
  a68=(a68+a71);
  a71=(a61*a74);
  a109=(a57*a49);
  a110=(a55*a12);
  a109=(a109+a110);
  a110=(a59*a109);
  a71=(a71-a110);
  a68=(a68+a71);
  if (res[1]!=0) res[1][26]=a68;
  a68=(a62*a49);
  a71=(a1*a68);
  a110=(a62*a12);
  a111=(a55*a110);
  a112=(a57*a68);
  a111=(a111+a112);
  a112=(a1*a111);
  a71=(a71+a112);
  a110=(a57*a110);
  a68=(a55*a68);
  a110=(a110-a68);
  a68=(a59*a110);
  a112=(a61*a111);
  a68=(a68+a112);
  a71=(a71+a68);
  if (res[1]!=0) res[1][27]=a71;
  a49=(a60*a49);
  a71=(a1*a49);
  a68=(a57*a49);
  a12=(a60*a12);
  a112=(a55*a12);
  a68=(a68+a112);
  a112=(a1*a68);
  a71=(a71+a112);
  a57=(a57*a12);
  a55=(a55*a49);
  a57=(a57-a55);
  a55=(a59*a57);
  a49=(a61*a68);
  a55=(a55+a49);
  a71=(a71+a55);
  a71=(-a71);
  if (res[1]!=0) res[1][28]=a71;
  a71=cos(a54);
  a55=(a53*a71);
  a54=sin(a54);
  a49=(a51*a54);
  a55=(a55-a49);
  a49=(a1*a55);
  a12=(a61*a55);
  a53=(a53*a54);
  a51=(a51*a71);
  a53=(a53+a51);
  a51=(a59*a53);
  a12=(a12-a51);
  a49=(a49+a12);
  if (res[1]!=0) res[1][29]=a49;
  a49=(a64*a71);
  a12=(a63*a54);
  a49=(a49+a12);
  a12=(a1*a49);
  a63=(a63*a71);
  a64=(a64*a54);
  a63=(a63-a64);
  a64=(a59*a63);
  a51=(a61*a49);
  a64=(a64+a51);
  a12=(a12+a64);
  if (res[1]!=0) res[1][30]=a12;
  a12=(a67*a54);
  a64=(a70*a71);
  a12=(a12+a64);
  a1=(a1*a12);
  a67=(a67*a71);
  a70=(a70*a54);
  a67=(a67-a70);
  a59=(a59*a67);
  a61=(a61*a12);
  a59=(a59+a61);
  a1=(a1+a59);
  a1=(-a1);
  if (res[1]!=0) res[1][31]=a1;
  if (res[2]!=0) res[2][0]=a10;
  if (res[2]!=0) res[2][1]=a21;
  a27=(-a27);
  if (res[2]!=0) res[2][2]=a27;
  if (res[2]!=0) res[2][3]=a15;
  if (res[2]!=0) res[2][4]=a17;
  if (res[2]!=0) res[2][5]=a8;
  if (res[2]!=0) res[2][6]=a20;
  if (res[2]!=0) res[2][7]=a24;
  if (res[2]!=0) res[2][8]=a33;
  if (res[2]!=0) res[2][9]=a44;
  a50=(-a50);
  if (res[2]!=0) res[2][10]=a50;
  if (res[2]!=0) res[2][11]=a38;
  if (res[2]!=0) res[2][12]=a40;
  if (res[2]!=0) res[2][13]=a31;
  if (res[2]!=0) res[2][14]=a43;
  if (res[2]!=0) res[2][15]=a47;
  if (res[2]!=0) res[2][16]=a58;
  if (res[2]!=0) res[2][17]=a66;
  a72=(-a72);
  if (res[2]!=0) res[2][18]=a72;
  if (res[2]!=0) res[2][19]=a60;
  if (res[2]!=0) res[2][20]=a62;
  if (res[2]!=0) res[2][21]=a56;
  if (res[2]!=0) res[2][22]=a65;
  if (res[2]!=0) res[2][23]=a69;
  if (res[2]!=0) res[2][24]=a78;
  if (res[2]!=0) res[2][25]=a86;
  a92=(-a92);
  if (res[2]!=0) res[2][26]=a92;
  if (res[2]!=0) res[2][27]=a80;
  if (res[2]!=0) res[2][28]=a82;
  if (res[2]!=0) res[2][29]=a76;
  if (res[2]!=0) res[2][30]=a85;
  if (res[2]!=0) res[2][31]=a89;
  if (res[3]!=0) res[3][0]=a34;
  if (res[3]!=0) res[3][1]=a98;
  a103=(-a103);
  if (res[3]!=0) res[3][2]=a103;
  if (res[3]!=0) res[3][3]=a104;
  a9=(-a9);
  if (res[3]!=0) res[3][4]=a9;
  a5=(-a5);
  if (res[3]!=0) res[3][5]=a5;
  if (res[3]!=0) res[3][6]=a18;
  a22=(-a22);
  if (res[3]!=0) res[3][7]=a22;
  a14=(-a14);
  if (res[3]!=0) res[3][8]=a14;
  if (res[3]!=0) res[3][9]=a42;
  if (res[3]!=0) res[3][10]=a36;
  if (res[3]!=0) res[3][11]=a26;
  if (res[3]!=0) res[3][12]=a48;
  if (res[3]!=0) res[3][13]=a105;
  a23=(-a23);
  if (res[3]!=0) res[3][14]=a23;
  if (res[3]!=0) res[3][15]=a7;
  if (res[3]!=0) res[3][16]=a2;
  a29=(-a29);
  if (res[3]!=0) res[3][17]=a29;
  if (res[3]!=0) res[3][18]=a91;
  if (res[3]!=0) res[3][19]=a96;
  a99=(-a99);
  if (res[3]!=0) res[3][20]=a99;
  if (res[3]!=0) res[3][21]=a100;
  a32=(-a32);
  if (res[3]!=0) res[3][22]=a32;
  a28=(-a28);
  if (res[3]!=0) res[3][23]=a28;
  if (res[3]!=0) res[3][24]=a41;
  a45=(-a45);
  if (res[3]!=0) res[3][25]=a45;
  a37=(-a37);
  if (res[3]!=0) res[3][26]=a37;
  if (res[3]!=0) res[3][27]=a0;
  if (res[3]!=0) res[3][28]=a93;
  if (res[3]!=0) res[3][29]=a97;
  if (res[3]!=0) res[3][30]=a94;
  if (res[3]!=0) res[3][31]=a101;
  a46=(-a46);
  if (res[3]!=0) res[3][32]=a46;
  if (res[3]!=0) res[3][33]=a30;
  if (res[3]!=0) res[3][34]=a16;
  a95=(-a95);
  if (res[3]!=0) res[3][35]=a95;
  if (res[3]!=0) res[3][36]=a79;
  if (res[3]!=0) res[3][37]=a90;
  a109=(-a109);
  if (res[3]!=0) res[3][38]=a109;
  if (res[3]!=0) res[3][39]=a110;
  a57=(-a57);
  if (res[3]!=0) res[3][40]=a57;
  a53=(-a53);
  if (res[3]!=0) res[3][41]=a53;
  if (res[3]!=0) res[3][42]=a63;
  a67=(-a67);
  if (res[3]!=0) res[3][43]=a67;
  a52=(-a52);
  if (res[3]!=0) res[3][44]=a52;
  if (res[3]!=0) res[3][45]=a84;
  if (res[3]!=0) res[3][46]=a81;
  if (res[3]!=0) res[3][47]=a3;
  if (res[3]!=0) res[3][48]=a74;
  if (res[3]!=0) res[3][49]=a111;
  a68=(-a68);
  if (res[3]!=0) res[3][50]=a68;
  if (res[3]!=0) res[3][51]=a55;
  if (res[3]!=0) res[3][52]=a49;
  a12=(-a12);
  if (res[3]!=0) res[3][53]=a12;
  if (res[3]!=0) res[3][54]=a11;
  if (res[3]!=0) res[3][55]=a25;
  a106=(-a106);
  if (res[3]!=0) res[3][56]=a106;
  if (res[3]!=0) res[3][57]=a107;
  a77=(-a77);
  if (res[3]!=0) res[3][58]=a77;
  a73=(-a73);
  if (res[3]!=0) res[3][59]=a73;
  if (res[3]!=0) res[3][60]=a83;
  a87=(-a87);
  if (res[3]!=0) res[3][61]=a87;
  a39=(-a39);
  if (res[3]!=0) res[3][62]=a39;
  if (res[3]!=0) res[3][63]=a19;
  if (res[3]!=0) res[3][64]=a13;
  if (res[3]!=0) res[3][65]=a102;
  if (res[3]!=0) res[3][66]=a6;
  if (res[3]!=0) res[3][67]=a108;
  a88=(-a88);
  if (res[3]!=0) res[3][68]=a88;
  if (res[3]!=0) res[3][69]=a75;
  if (res[3]!=0) res[3][70]=a4;
  a35=(-a35);
  if (res[3]!=0) res[3][71]=a35;
  return 0;
}

CASADI_SYMBOL_EXPORT int pf_and_J(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pf_and_J_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pf_and_J_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pf_and_J_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pf_and_J_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pf_and_J_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pf_and_J_incref(void) {
}

CASADI_SYMBOL_EXPORT void pf_and_J_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pf_and_J_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int pf_and_J_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real pf_and_J_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pf_and_J_name_in(casadi_int i) {
  switch (i) {
    case 0: return "q";
    case 1: return "theta";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pf_and_J_name_out(casadi_int i) {
  switch (i) {
    case 0: return "y";
    case 1: return "Jy";
    case 2: return "DyDtheta";
    case 3: return "dJy_dtheta";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pf_and_J_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pf_and_J_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pf_and_J_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int pf_and_J_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
